version: '3.7'

services:
  web:
    build: .      
    restart: always    
    command: gunicorn --bind 0.0.0.0:5000 project:app 
    ports:
      - 5000:5000
    env_file:
      - ./dev.env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./dev_db.env
    
volumes:
  postgres_data: